# Generated by Django 4.1.5 on 2023-01-10 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='crated_date',
            new_name='created_date',
        ),
    ]
