# Generated by Django 4.1.5 on 2023-01-14 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_crated_date_comments_created_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-created_date']},
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='approach',
            new_name='approved',
        ),
    ]
